version: '3.8'

services:
  backend:
    image: rakeshvanam1/backend-image:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/coursedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Raki@6868
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: rakeshvanam1/frontend-image:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Raki@6868
      POSTGRES_DB: coursedb
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
